# -*- coding: utf-8 -*-
"""Finalrevised code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0MGtngy3GYMJN587NuCQwHqPu90NS3y
"""

# =========================================
# FAST FASHION-MNIST CNN (COLAB-FRIENDLY)
# =========================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix
import os

# -----------------------------------------
# 1. LOAD AND REDUCE DATASET (SPEED-UP)
# -----------------------------------------
(trainX, trainy), (testX, testy) = fashion_mnist.load_data()

# Reduce dataset size for fast iteration
trainX, trainy = trainX[:1000], trainy[:1000]
testX, testy = testX[:200], testy[:200]

# Normalize and reshape
trainX = (trainX / 255.0).astype("float32")[..., None]
testX = (testX / 255.0).astype("float32")[..., None]

print("Train shape:", trainX.shape)
print("Test shape:", testX.shape)

# -----------------------------------------
# 2. VISUALIZE SAMPLE IMAGES
# -----------------------------------------
plt.figure(figsize=(6,6))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(trainX[i].squeeze(), cmap="gray")
    plt.axis("off")
plt.show()

# -----------------------------------------
# 3. MODEL DEFINITION (SMALL + FAST)
# -----------------------------------------
def build_model():
    model = Sequential([
        Conv2D(32, (3,3), activation="relu", input_shape=(28,28,1)),
        MaxPooling2D((2,2)),
        Flatten(),
        Dense(64, activation="relu"),
        Dense(10, activation="softmax")
    ])
    return model

model = build_model()

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"]
)

model.summary()

# -----------------------------------------
# 4. TRAIN MODEL (FAST)
# -----------------------------------------
history = model.fit(
    trainX,
    trainy,
    epochs=2,
    batch_size=64
    ,
    validation_split=0.3,
    verbose=2
)

# -----------------------------------------
# 5. PLOT TRAINING CURVES
# -----------------------------------------
plt.plot(history.history["sparse_categorical_accuracy"])
plt.plot(history.history["val_sparse_categorical_accuracy"])
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend(["Train", "Validation"])
plt.show()

# -----------------------------------------
# 6. SINGLE PREDICTION EXAMPLE
# -----------------------------------------
labels = [
    "t-shirt", "trouser", "pullover", "dress", "coat",
    "sandal", "shirt", "sneaker", "bag", "ankle boot"
]

prediction = model.predict(testX[:1])
predicted_label = labels[np.argmax(prediction)]

print("Predicted label:", predicted_label)
plt.imshow(testX[0].squeeze(), cmap="gray")
plt.axis("off")
plt.show()

# -----------------------------------------
# 7. CONFUSION MATRIX
# -----------------------------------------
y_pred = model.predict(testX).argmax(axis=1)
cm = confusion_matrix(testy, y_pred)

os.makedirs("figures", exist_ok=True)

plt.figure(figsize=(7,6))
sns.heatmap(cm, cmap="Blues", fmt="d")
plt.title("Confusion Matrix – Fashion MNIST")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.tight_layout()
plt.savefig("figures/confusion_matrix.png", dpi=150)
plt.show()